printf: handle Array and Map
fiji-flo/gtmpl-rust pull request #26
Opened 2021-06-21 16:52 UTC by flavio

Handle printing of `%v` with Array and Map objects.

Obviously this won't cover 100% of the cases, but it's better than

2021-07-14 09:07 UTC, flavio commented
@fiji-flo hi, any chance to get this PR reviewed? :pleading_face:

2021-07-27 12:11 UTC, fiji-flo requested changes
Thanks for this PR @flavio 

Could you make it behave like golang `fmt.Printf` (see https://play.golang.org/p/3AR2Vlf7FWc) and remove the regex dependency?

I'll get back to you faster next time. I had some busy weeks.

2021-07-27 12:11 UTC, fiji-flo commented on src/printf.rs
> +        assert!(Regex::new(r"^foo \{.*\}$").unwrap().is_match(&s));
We could check `starts_with("foo {")` and `ends_with("}")` to skip the regex dependency.

2021-08-04 10:24 UTC, flavio commented
@fiji-flo, sorry for the late response. I was on vacation :)

I've updated the PR to address your notes. Note well, the rendering of arrays was already fine (unless I missed something), I fixed the rendering of maps.

Once you're happy with the code I can squash the 3 commits into a single one, unless you prefer to merge the branch as it is

2021-08-06 05:51 UTC, fiji-flo requested changes
Looks great, thanks a lot. If you could adopt the nit pick there I'll merge and create a 0.7.1 release 🥂

2021-08-06 05:51 UTC, fiji-flo commented on src/printf.rs
> +        assert!(s.ends_with("]"));
```suggestion
    assert!(s == "foo map[number:42 hello:world]" || s == "foo map[hello:world number:42]");
```
That's simpler and tests the white space between pairs. (Potentially needs formatting)

2021-08-06 07:15 UTC, flavio commented
@fiji-flo I've accepted the change, fixed the indentation, ran the tests and then squashed everything into a single commit

Thanks for your reviews!

2021-08-06 08:30 UTC, fiji-flo approved these changes
👍 Thanks. I'll fix the clippy warnings (that's on me) and get it released.

2021-08-06 08:31 UTC, merged

2021-08-06 09:10 UTC, flavio commented
@fiji-flo just out of curiosity, how do you handle release? I wanted to subscribe to release events to get notified about the `0.7.1` release, but I noticed no release has ever done and no git tags are associated to the repo :thinking:

2021-08-06 09:13 UTC, fiji-flo commented
I've never automated it. That's on my TODO for all my crates to move this into a github action. But I published it already.

I'll move to branches for the `0.X` and tags for releases then.